### PR TITLE
Image preload

### LINKED ISSUE #132: need a documented way to preload images

### PR DESCRIPTION
**Pull request by guydav**
Resolves #132

### CODE REVIEW

**Comment by gureckis** [comment]
i have another idea about this.  so what id find most intuitive would be if when im writing my "page" level component if i could provide a function called `preload()` that did the things i need to have it do before it even is loaded.  the router/timeline object could when navigating to a route always asynchronously call `next.preload()` to get ready.  with the idea being that this lets you specify more "locally" what preload is needed for your component without preloading everything all at once.  and of course from there you could do other things like preload all the routes up front something if that works for your use case.  this also makes the components more encapsulated so you could share them between experiments without a lot of extra code in different places to trigger the preload.

**Comment by guydav** [comment]
I'm thinking about this and trying to imagine how we might implement this -- I can imagine a couple of options: 
1. A fairly manual option I can imagine is to add it to the route definitions -- so something like the below:
```javascript
timeline.pushSeqRoute({
  path: '/consent',
  name: 'consent',
  component: Consent,
  preload: <something>
})
```
and then the default route guard added by `router.js:addGuards` would call the preload if you're allowed to move to the route. The upside is that it's absolutely clear what happens, but the downside is that you have to configure it manually.

2. The less manual option is that we check (maybe also in `router.js:addGuards`) if the component exports something (perhaps named `preload`), and if it does, we call it automatically. The upside is that it's cognitively 'free' to the user -- you implement `preload` and it just happens. The downside is that it might get called every time the route happens. The ways around that are either keeping track somewhere in the router of whether a particular component's preload was called, or this being the user's responsibility in implementing their preload to run this sort of check. 

One more minor issue to think about is that we can't provide one implementation, because at least in the fashion I've implemented it, the `import.meta.glob` requires the path to be fixed -- because Vite needs to optimize it, you can't provide it in runtime. So the best we could do is provide a template/design pattern, so that's fine?

**Comment by gureckis** [comment]
option 2 seems nicer from not having to configure but I poked around briefly and I'm not sure that you can really access function defined inside a SFC from outside that component or before it is loaded so possibly option 1 is the only feasible one?  perhaps there's a clever trick to make it work.  The option 1 also you can see in the current app_timeline.js that we do show examples of a custom `beforeEnter` when it was necessary:

```
timeline.pushSeqRoute({
  path: '/welcome/:service',
  name: 'welcome_referred',
  component: Advertisement,
  meta: {
    prev: undefined,
    next: 'consent',
    allowDirectEntry: true,
    requiresConsent: false,
  }, // override what is next
  beforeEnter: (to) => {
    processQuery(to.query, to.params.service)
  },
})
```

**Comment by guydav** [comment]
Why not use `beforeEnter`? I implemented something that seems to work with it.

**Comment by gureckis** [comment]
I think we want it to be like onenter for the route before the current one.  so like start loading images for /demographic while looking at /consent.  so that when you actually do get to /demographic the resources are preloaded.  if you wait until beforeEnter it will trigger the fetching but the component will load within milliseconds visually and you might get some delay as images appear.

**Comment by guydav** [comment]
I think the thing that's unhappy there is that it breaks some degree of abstraction -- that requires you to do this in one/multiple places where one might enter the component, as opposed to being tied to the component itself. 

Also there isn't really a onenter -- it can be in the `beforeEnter` on the previous route and run async, or it can be in a global `afterEach` hook, but then that's also decoupled from the route definition and needs to be configured somewhere else.

**Comment by gureckis** [comment]
i think what you said before works.  new property if routes is `preload` which is called by the route which is the parent of that node in the timeload `beforeenter`.  can talk more in person...

**Pull request merged**
